### ISSUE TITLE
auth_googleoauth2/invalidstateparam Error

### ISSUE THREAD

**Issue by fmsabeti** [rabser/moodle-auth_googleoauth2#163]
Hi there,

First time poster, so please excuse any netiquette mistakes here. We're running Moodle 2.9 (Build: 20150511) and trying to use Google as our authentication through OAuth2 version 2.1 (Build: 2015090200). We're running into an error noted above, and when we try to authenticate, it opens the Google login window, but following login, returns to moodle with the error: auth_googleoauth2/invalidstateparam

We have enabled Google+ API. Any other advice or help that you might have would be great!

Thanks!
##

**Comment by mouneyrac** [comment]
I remember seen this issue because I had twice a provider button displayed on the page (i added it in the top header menu so it appeares twice on the login page) and the plugin doesn't support it yet.

**Comment by fmsabeti** [comment]
Thank you for the prompt response and help!

This is what our site looks like (images below); are you referring to the
Login screen that shows the Google sign in button, or the two links labeled
'Log in' at the top and bottom? I'm not sure how to remove these, but if it
will fix our authentication, I will find out!

Thank you again.

[image: Inline image 1][image: Inline image 2]

Farhad Mordechai Sabeti
Director of Education, General Studies
Bnei Akiva Schools of Toronto
416.630.6772 ext. 33
sabeti@bastoronto.org

**Comment by tillmad** [comment]
I mentioned that my students were occasionally having issues with the Oauth2 plugin.

I haven't been able to replicate it reliably at all, but have asked them to send me screenshots when they have issues.

Today I received the InvalidStateParam error.  I have had debugging turned on so I can provide info on the Oauth2 error if it occurs for me.  

auth_googleoauth2/invalidstateparam

More information about this error

Debug info: 
Error code: invalidstateparam
$a contents:
Stack trace:
line 74 of /auth/googleoauth2/lib.php: moodle_exception thrown
line 19 of /auth/googleoauth2/google_redirect.php: call to googleoauth2_provider_redirect()

<img width="789" alt="screen shot 2015-11-19 at 8 22 49 am" src="https://cloud.githubusercontent.com/assets/15927035/11273262/df8b3eb2-8e97-11e5-98c3-58c1f10f677b.png">

**Comment by tillmad** [comment]
I should say this is in Moodle 2.9.2+ (Build: 20151008)
Oauth2 plugin 2.2 (Build: 2015110600)

I was using a Mac with Google Chrome browser

**Comment by Saamarthya** [comment]
Hi Guys,
Is this issue resolved? I am also facing a similar issue on my website, www.saamarthyaved.com

Thanks.

**Comment by danielneis** [comment]
Hello,

we at www.moodlebrasil.org have updated the plugin and found similar issue.
We've found that the old buttons that were added to the moodle/blocks/block_login.php did not work anymore, but the ones added on the login screen by the auth_googleoauth2_display_buttons() does work, so we've changed the block to generated the buttons with this function instead of the HTML used before and it worked.

Kind regards,
Daniel

**Comment by richardsite** [comment]
line 74 of /auth/googleoauth2/lib.php: moodle_exception thrown Moodle 2.9

[Fri Apr 01 11:16:46.441469 2016] [:error] [pid 19100] [client IP] PHP Notice:  Undefined index: oauth2state_facebook in /var/www/html/SITE/moodle/auth/googleoauth2/lib.php on line 73, referer: https://www.facebook.com
[Fri Apr 01 11:16:46.442519 2016] [:error] [pid 19100] [client IP] Default exception handler: auth_googleoauth2/invalidstateparam Debug: \nError code: invalidstateparam\n$a contents: \n* line 74 of /auth/googleoauth2/lib.php: moodle_exception thrown\n* line 19 of /auth/googleoauth2/facebook_redirect.php: call to googleoauth2_provider_redirect()\n, referer: https://www.facebook.com


When trying to enter the copied link url (https://www.facebook.com/v2.2/dialog/oauth?client_id=######&redirect_uri=URL%2Fauth%2Fgoogleoauth2%2Ffacebook_redirect.php&state=#####&scope=email&response_type=code&approval_prompt=auto
) generates the error, but if accessed by the generated image by the utility can be accessed without error.

Apparently the problem is that it changes the session and is generated when creating the enter button with facebook.

Al tratar de entrar con el enlace copiado del url (https://www.facebook.com/v2.2/dialog/oauth?client_id=######&redirect_uri=URL%2Fauth%2Fgoogleoauth2%2Ffacebook_redirect.php&state=#####&scope=email&response_type=code&approval_prompt=auto
) genera el error, pero si se accede por el que se genera por la utilería se puede acceder sin error.

Al parecer el problema es que cambia la session y se genera al crear el botón de entrar con facebook
