### ISSUE TITLE
Google Login Button Disappeared When Upgrading to Moodle 3.2.2

### ISSUE THREAD

**Issue by agujoa** [rabser/moodle-auth_googleoauth2#237]
Hi,

Our Oauth Google login button which had previously been working on Moodle 2.9 has disappeared after upgrading to Moodle 3.2.2... We have tried generating a new set of codes from the Google admin console and replaced the old codes, but the Google Login button still does not appear...
Can you kindly advise if this is a Google, Moodle, or Oauth problem, and how do we resolve please?
Many thanks,
Angelo

**Comment by rabser** [comment]
I did a test with moodle 3.2.2+ and the actual plugin release: all works fine, except if you enabled _loginhttps_ option in moodle (you did ??). I'm working on a new release of this plugin with many changes and updates in code: if you would to test this new one, i can send you a preview of this work-in-progress.
The only "bad" thing is that BattleNet actually is not supported anymore.

**Comment by Flottertotte** [comment]
Same problem here. Linkedin and FB don't show up anymore.

**Comment by rabser** [comment]
Did you enable loginhttps ?
Only linkedin and FB disappear or other provider are shown ?

**Comment by Flottertotte** [comment]
Yes, I have https enabled. 
I only have FB and Linkedin activated so at the moment I only can report this. If you want I can help also with other places but it seems it is a general issue, not related to FB and Linkedin specifically.

**Comment by rabser** [comment]
I'm sorry, https enabled on all the site, or only for login purposes ?
Do you feel good in changing php code ?

**Comment by mouneyrac** [comment]
Hi guys, just some ideas on this issue that happened a few times to me, the button may not show up due to one of these things (just idea in my mind):
* cache issue (the login page is cached without button code) - purge your Moodle cache (and your browser cache, never know...)
* the way js is loaded in Moodle - the code inserting the button (script.js) may be triggered before the login page html is renderer. You could make the insert button javascript code be called at the footer on your theme as the solution. Or try to check when it is run with chrome inspector/debugger.
* you use a very different Moodle theme (but it is unlikey, to not work, the login page should have different text input name for "username" field and no "auth_custom_location" tag id) and so you need to rewrite the js for matching your login page.
* finally, and this is the way the button used to be displayed before inserting them by Javascript, you must write the button display code yourself into your login page, it is just one line (and you must disable the button been displayed automatically by the plugin, I think the display option is still in the plugin admin settings page?)

**Comment by rabser** [comment]
Hi, i found one little bug in lib.php and one in auth.php that can be the source of problems in loading the button interface properly:

The script js should be loaded as follow in auth.php:
$PAGE->requires->js(new moodle_url($CFG->httpswwwroot . "/auth/googleoauth2/script.js"));

and in lib.php there is a type error in 
singinprovider -> signinprovider in the onclick method call.

With these changes, every moodle (since 3.2.2+) displays the button interface correctly.
All these changes are fixed in 3.0 with many other little things: i'm getting all the requests from github issues and coding them, so i need more time (twitter is a panic...) .

**Comment by Flottertotte** [comment]
Hi all,

I did the following to make both buttons (FB and Linkedin) appear:

1. In the config file, I changed the www root from http to https (I had in moodle activated https but the config file contained the www root with http
3. I also added a .httaccess file to the root folder to force https (otherwise I got a warning when I just entered "www..." into the browser):
```
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
These 2 things made them finally appear.

The only problem is now, that the FB login does not work (auth_googleoauth2/couldnotgetuseremail) I will opened a [separate issue](https://github.com/rabser/moodle-auth_googleoauth2/issues/239) for that:

**Comment by rabser** [comment]
Ok, the problem seems the uncorrect path for loading script.js, but your solution with the Rewrite rules can give you more problems than solved ones.
So, rollback these changes (in apache i believe) and try to pull the latest code from this repo/master: i did the small changes that should solve the button disappearing in moodle 3.x.

**Comment by Flottertotte** [comment]
I tried your solution but now the login screen is white.

**Comment by rabser** [comment]
Could you send me the latest rows (in pm if you won't publish them on github) of your webserver error_log ?

**Comment by rabser** [comment]
A doubt: if you download only the plugin from the repository, you need to launch composer to download all the package dependecies, as described in the README.md

**Comment by Flottertotte** [comment]
Thanks and your guess was right (and I wondered why the downloaded zip package was so small ...). Now both buttons appear

**Comment by rabser** [comment]
Good news!
Stay tuned, in the next few week i'll post a new release of this plugin, with some enhancements and code update/refactor.
Last but not least, the buttons appear, but they works ? :-)

**Comment by mouneyrac** [comment]
Can't wait to test it :) Thanks Sergio!
