### ISSUE TITLE
500 Server Error - Dangerously writable - error/auth googleoauth2/couldnotgetgoogleaccesstoken

### ISSUE THREAD

**Issue by sintjago** [rabser/moodle-auth_googleoauth2#43]
Hi,

Thank you for making this. This is great. I am having a small problem that its probably simple to fix but I cant figure it out. I tried it in two sites to see if the problem was one of my sites. They are both hosted at Justhost.com. I am getting this same error on my two sites with both Google and Facebook, but the Windows Live is working fine. I am thinking its my security settings but not sure. 

500 Server Error

A misconfiguration on the server caused a hiccup. Check the server logs, fix the problem, then try again.
URL: http://cursosctc.com/moodle/auth/googleoauth2/facebook_redirect.php?code=AQAC-rVSfF6SemxJ9Txwc61HUh9SsYRgqDcNgkDXKrJVV8jplAiTnHFPs67o_66CCMkWDhp6pa_Dcwabvwu4LldunRYtF5_sACsBRKPyX3mGSPpI_bqS8jLmNr0tOzUGwM3wBoq9JdskXqycNirwe1T7xjQ3EuD2JXkVmFhvPgnd4lJBEfX3WuXAV23rBNFPhGsi9YqjDaDZPoQGlrzkPxRaArvIro9tvLe3T7pzuCCqOB4UAD-E_aUXipAhj3A_hl1YPArgX8SJe48vts0rPIGl6DjTA
Dangerously writable: [/home3/cursosct/public_html/moodle/auth/googleoauth2/facebook_redirect.php]
FIXED

**Comment by maliky** [comment]
I moved form a shared hosting environnement on bluehost to a VPS on OVH hoping it would resolve my connection problem but not.  Althoug I do not get the couldnotgetgoogleaccesstoken but the faileduserdetails.  
Could it be because I don't have a certified certificate on my IP ?  If so my students will have to way some more until I can pay and install that.

**Comment by cme0848** [comment]
I had the same error "Error 500 - Dangerously Writeable". Then I went to my server log (which can be easily accessed on a shared host like Bluechip, Hostgater, Hostmonster,etc). The error stated
`[Mon May 01 11:37:00 2017] [error] [client 23.24.136.177] SoftException in Application.cpp:256: File "/home4/<DOMAINUSER>/public_html/CRM/index.php" is writeable by group
[Mon May 01 11:37:00 2017] [error] [client 23.24.136.177] Premature end of script headers: index.php`

I changed the permissions of the files inside of the CRM folder to 755 and the issue was resolved. Hope this helps
